Update nginx.conf.web.template
zextras/carbonio-proxy pull request #128
Opened 2024-09-04 09:20 UTC by lfasci

chore: fix preview https://zextras.atlassian.net/browse/PREV-141

2024-09-04 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-proxy?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-proxy?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-proxy?pullRequest=128) it.</sub>

2024-09-04 09:39 UTC, MaryTishchenkova approved these changes

2024-09-04 20:05 UTC, M0Rf30 commented
I would move these lines in a location in order to have a more limited scope
Here should be fine
https://github.com/zextras/carbonio-proxy/blob/devel/conf/nginx/templates/nginx.conf.web.https.default.template#L108

(only affects `/static` requests )

location context is supported for custom mime declarations
https://nginx.org/en/docs/http/ngx_http_core_module.html#types

2024-09-04 20:07 UTC, M0Rf30 requested changes

2024-09-04 20:07 UTC, M0Rf30 commented on conf/nginx/templates/nginx.conf.web.template
> +    types
I would move these lines in a location in order to have a more limited scope
Here should be fine
https://github.com/zextras/carbonio-proxy/blob/devel/conf/nginx/templates/nginx.conf.web.https.default.template#L108

(only affects /static requests )

location context is supported for custom mime declarations
https://nginx.org/en/docs/http/ngx_http_core_module.html#types

2024-09-11 10:13 UTC, lfasci commented
I never tested the change on other file, it should be tested on all http* templates, because mjs was never used i don't think it can conflicts with other parts.
In short: approve as is or let's start testing with http* templates.

2024-09-11 10:19 UTC, closed without merging